/*
8
criar um formulário que nos permita selecionar uma cor, e, consoante a cor seleciona,
mostra o texto escrito no campo de texto.
 */
package checkBox;

/**
 *
 * @author Douglas Graça
 */
public class Exerc08 extends javax.swing.JFrame {

    /**
     * Creates new form Exerc08
     */
    public Exerc08() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoCor = new javax.swing.ButtonGroup();
        chkverde = new javax.swing.JCheckBox();
        chkvermelho = new javax.swing.JCheckBox();
        chkamarelo = new javax.swing.JCheckBox();
        btnAceitar = new javax.swing.JButton();
        txtCor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grupoCor.add(chkverde);
        chkverde.setText("Verde");

        grupoCor.add(chkvermelho);
        chkvermelho.setText("Vermelho");
        chkvermelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkvermelhoActionPerformed(evt);
            }
        });

        grupoCor.add(chkamarelo);
        chkamarelo.setText("Amarelo");

        btnAceitar.setText("Aceitar");
        btnAceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceitarActionPerformed(evt);
            }
        });

        txtCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkamarelo)
                        .addComponent(chkvermelho)
                        .addComponent(chkverde))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceitar)
                        .addGap(4, 4, 4)))
                .addGap(44, 44, 44)
                .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(chkverde)
                .addGap(37, 37, 37)
                .addComponent(chkvermelho)
                .addGap(42, 42, 42)
                .addComponent(chkamarelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceitar)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkvermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkvermelhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkvermelhoActionPerformed

    private void txtCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorActionPerformed

    private void btnAceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceitarActionPerformed

        String msg  = "cor escolhida: "; 
        if (chkamarelo.isSelected()){
            msg = msg + "amarelo";
            
        }
        
        if (chkvermelho.isSelected()){
            msg = msg + "vermelho";
            
        }
         if (chkverde.isSelected()){
            msg = msg + "verde";
            
        }
        
        txtCor.setText(msg);
    }//GEN-LAST:event_btnAceitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exerc08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exerc08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exerc08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exerc08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exerc08().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceitar;
    private javax.swing.JCheckBox chkamarelo;
    private javax.swing.JCheckBox chkverde;
    private javax.swing.JCheckBox chkvermelho;
    private javax.swing.ButtonGroup grupoCor;
    private javax.swing.JTextField txtCor;
    // End of variables declaration//GEN-END:variables
}
